# drink_database.py
# Expanded drink database for bars/pubs
# Categories: beer, wine, spirits
# Includes subcategories: mid-strength beers, sparkling wines, etc.

DRINK_DATABASE = {
    "beer": {
        "lager": [
            {"name": "Heineken", "abv": 5.0, "origin": "Netherlands", "profile": "Crisp, slightly bitter"},
            {"name": "Budweiser", "abv": 5.0, "origin": "USA", "profile": "Light, easy drinking"},
            {"name": "Corona Extra", "abv": 4.5, "origin": "Mexico", "profile": "Light, crisp"},
            {"name": "Stella Artois", "abv": 5.2, "origin": "Belgium", "profile": "Smooth, malty"},
            {"name": "Peroni Nastro Azzurro", "abv": 5.1, "origin": "Italy", "profile": "Light, slightly bitter"},
            {"name": "Asahi Super Dry", "abv": 5.0, "origin": "Japan", "profile": "Clean, crisp"},
            {"name": "Pilsner Urquell", "abv": 4.4, "origin": "Czech Republic", "profile": "Malty, hoppy"},
            {"name": "Beck's", "abv": 5.0, "origin": "Germany", "profile": "Crisp, light"},
            {"name": "Sapporo Premium", "abv": 5.0, "origin": "Japan", "profile": "Smooth, clean"},
            {"name": "Tiger Beer", "abv": 5.0, "origin": "Singapore", "profile": "Light, refreshing"},
            {"name": "Carlsberg", "abv": 5.0, "origin": "Denmark", "profile": "Smooth, easy drinking"},
            {"name": "Tuborg", "abv": 4.6, "origin": "Denmark", "profile": "Light, crisp"},
            {"name": "Kirin Ichiban", "abv": 5.0, "origin": "Japan", "profile": "Smooth, clean"},
            {"name": "Bitburger Premium Pils", "abv": 4.8, "origin": "Germany", "profile": "Crisp, dry"},
            {"name": "Warsteiner", "abv": 4.8, "origin": "Germany", "profile": "Smooth, light"},
            {"name": "Holsten Pilsner", "abv": 4.8, "origin": "Germany", "profile": "Crisp, hoppy"},
            {"name": "Grolsch Premium Lager", "abv": 5.0, "origin": "Netherlands", "profile": "Malty, smooth"},
            {"name": "San Miguel Pale Pilsen", "abv": 5.0, "origin": "Philippines", "profile": "Light, crisp"},
            {"name": "Lion Lager", "abv": 4.8, "origin": "Sri Lanka", "profile": "Smooth, mild"},
            {"name": "Peroni Leggera", "abv": 4.1, "origin": "Italy", "profile": "Light, crisp"},
            {"name": "Baltika No. 3", "abv": 4.8, "origin": "Russia", "profile": "Mild, malty"},
            {"name": "Efes Pilsen", "abv": 5.0, "origin": "Turkey", "profile": "Light, crisp"},
            {"name": "Foster's Lager", "abv": 5.0, "origin": "Australia", "profile": "Smooth, light"},
            {"name": "Victoria Bitter", "abv": 4.9, "origin": "Australia", "profile": "Malty, bitter"},
            {"name": "Coopers Original Pale Ale", "abv": 5.0, "origin": "Australia", "profile": "Fruity, hoppy"},
            {"name": "Tiger Crystal", "abv": 4.8, "origin": "Singapore", "profile": "Light, refreshing"},
            {"name": "Asahi Dry Black", "abv": 5.0, "origin": "Japan", "profile": "Roasted, smooth"},
            {"name": "Bintang", "abv": 4.7, "origin": "Indonesia", "profile": "Crisp, light"},
            {"name": "Chang Beer", "abv": 5.0, "origin": "Thailand", "profile": "Smooth, light"},
            {"name": "Tsingtao", "abv": 4.7, "origin": "China", "profile": "Crisp, light"},
            {"name": "Kingfisher Premium Lager", "abv": 4.8, "origin": "India", "profile": "Smooth, mild"},
            {"name": "Faxe Premium Lager", "abv": 5.0, "origin": "Denmark", "profile": "Full-bodied, crisp"},
            {"name": "Modelo Especial", "abv": 4.4, "origin": "Mexico", "profile": "Light, easy drinking"},
            {"name": "Dos Equis Lager", "abv": 4.5, "origin": "Mexico", "profile": "Crisp, refreshing"},
            {"name": "Kingfisher Ultra", "abv": 4.8, "origin": "India", "profile": "Smooth, mild"},
            {"name": "Sierra Nevada Pale Lager", "abv": 4.6, "origin": "USA", "profile": "Crisp, balanced"},
            {"name": "Amstel Light", "abv": 3.5, "origin": "Netherlands", "profile": "Light, easy drinking"},
            {"name": "Bud Light", "abv": 4.2, "origin": "USA", "profile": "Light, crisp"},
            {"name": "Coors Light", "abv": 4.2, "origin": "USA", "profile": "Light, clean"},
            {"name": "Miller Lite", "abv": 4.2, "origin": "USA", "profile": "Light, crisp"},
            {"name": "Peroni Gran Riserva", "abv": 5.6, "origin": "Italy", "profile": "Smooth, balanced"},
            {"name": "Budweiser Budvar", "abv": 5.0, "origin": "Czech Republic", "profile": "Mild, malty"},
            {"name": "Pabst Blue Ribbon", "abv": 4.7, "origin": "USA", "profile": "Light, smooth"},
            {"name": "Molson Canadian", "abv": 5.0, "origin": "Canada", "profile": "Crisp, light"},
            {"name": "Labatt Blue", "abv": 5.0, "origin": "Canada", "profile": "Light, refreshing"},
            {"name": "Krombacher Pils", "abv": 4.8, "origin": "Germany", "profile": "Crisp, hoppy"},
            {"name": "Beck's Blue", "abv": 0.05, "origin": "Germany", "profile": "Non-alcoholic, light"},
            {"name": "Clausthaler Dry Hopped", "abv": 0.5, "origin": "Germany", "profile": "Non-alcoholic, hoppy"},
            {"name": "Budweiser Zero", "abv": 0.0, "origin": "USA", "profile": "Non-alcoholic, smooth"},
            {"name": "Heineken 0.0", "abv": 0.0, "origin": "Netherlands", "profile": "Non-alcoholic, crisp"},
            {"name": "Suntory The Premium Malt's", "abv": 5.5, "origin": "Japan", "profile": "Rich, malty"},
            {"name": "Orion Draft", "abv": 5.0, "origin": "Japan", "profile": "Light, crisp"},
            {"name": "Brahma", "abv": 4.3, "origin": "Brazil", "profile": "Light, smooth"},
            {"name": "Skol Lager", "abv": 4.7, "origin": "Brazil", "profile": "Light, easy drinking"},
            {"name": "Castle Lager", "abv": 5.0, "origin": "South Africa", "profile": "Crisp, full-bodied"},
            {"name": "Savanna Dry", "abv": 5.0, "origin": "South Africa", "profile": "Crisp, light"}
        ]
        "ale": [
        {"name": "Coopers Pale Ale", "abv": 4.5, "origin": "Australia", "profile": "Fruity, hoppy"},
        {"name": "Sierra Nevada Pale Ale", "abv": 5.6, "origin": "USA", "profile": "Citrus, piney"},
        {"name": "Fuller's London Pride", "abv": 4.7, "origin": "UK", "profile": "Balanced, malty"},
        {"name": "Little Creatures Pale Ale", "abv": 5.2, "origin": "Australia", "profile": "Hoppy, citrus"},
        {"name": "Goose Island Amber Ale", "abv": 5.9, "origin": "USA", "profile": "Malty, caramel"},
        {"name": "Stone Pale Ale", "abv": 5.8, "origin": "USA", "profile": "Bold, citrusy"},
        {"name": "Redback Ale", "abv": 4.6, "origin": "Australia", "profile": "Smooth, malty"},
        {"name": "Pavement Ale", "abv": 5.0, "origin": "USA", "profile": "Hoppy, floral"},
        {"name": "Samuel Smith's Pale Ale", "abv": 5.0, "origin": "UK", "profile": "Light, balanced"},
        {"name": "Dogfish Head 60 Minute IPA", "abv": 6.0, "origin": "USA", "profile": "Hoppy, bitter"},
        {"name": "BrewDog Punk IPA", "abv": 5.6, "origin": "Scotland", "profile": "Tropical, hoppy"},
        {"name": "Anchor Liberty Ale", "abv": 5.9, "origin": "USA", "profile": "Citrus, bold"},
        {"name": "Fuller's ESB", "abv": 5.9, "origin": "UK", "profile": "Malty, balanced"},
        {"name": "Brooklyn Brown Ale", "abv": 5.6, "origin": "USA", "profile": "Nutty, smooth"},
        {"name": "Coopers Best Extra Stout", "abv": 6.3, "origin": "Australia", "profile": "Roasted, rich"},
        {"name": "Harviestoun Old Engine Oil", "abv": 6.3, "origin": "Scotland", "profile": "Strong, roasted"},
        {"name": "Fuller's ESB", "abv": 5.9, "origin": "UK", "profile": "Balanced, malty"},
        {"name": "Newcastle Brown Ale", "abv": 4.7, "origin": "UK", "profile": "Smooth, caramel"},
        {"name": "Adnams Southwold Bitter", "abv": 4.0, "origin": "UK", "profile": "Light, hoppy"},
        {"name": "Timothy Taylor Landlord", "abv": 4.3, "origin": "UK", "profile": "Fruity, balanced"},
        {"name": "Thornbridge Jaipur IPA", "abv": 5.9, "origin": "UK", "profile": "Hoppy, citrusy"},
        {"name": "Baltic Amber Ale", "abv": 5.5, "origin": "Baltic Region", "profile": "Malty, smooth"},
        {"name": "Weihenstephaner Original", "abv": 5.1, "origin": "Germany", "profile": "Malty, slightly bitter"},
        {"name": "Ayinger Celebrator Doppelbock", "abv": 6.7, "origin": "Germany", "profile": "Malty, rich"},
        {"name": "Paulaner Salvator", "abv": 7.9, "origin": "Germany", "profile": "Strong, malty"},
        {"name": "Samuel Adams Boston Ale", "abv": 5.0, "origin": "USA", "profile": "Balanced, hoppy"},
        {"name": "Dogfish Head Indian Brown Ale", "abv": 7.0, "origin": "USA", "profile": "Strong, hoppy"},
        {"name": "Deschutes Black Butte Porter", "abv": 5.2, "origin": "USA", "profile": "Roasted, chocolatey"},
        {"name": "Young's Bitter", "abv": 3.7, "origin": "UK", "profile": "Light, malty"},
        {"name": "Old Speckled Hen", "abv": 5.2, "origin": "UK", "profile": "Malty, smooth"},
        {"name": "Robinsons Unicorn", "abv": 4.0, "origin": "UK", "profile": "Fruity, smooth"},
        {"name": "Black Sheep Ale", "abv": 4.4, "origin": "UK", "profile": "Smooth, hoppy"},
        {"name": "Fuller's 1845", "abv": 5.0, "origin": "UK", "profile": "Balanced, malty"},
        {"name": "Old Speckled Hen Gold", "abv": 4.2, "origin": "UK", "profile": "Light, fruity"},
        {"name": "Hobgoblin Ruby Ale", "abv": 5.0, "origin": "UK", "profile": "Malty, smooth"},
        {"name": "Bells Two Hearted Ale", "abv": 7.0, "origin": "USA", "profile": "Hoppy, piney"},
        {"name": "Lagunitas IPA", "abv": 6.2, "origin": "USA", "profile": "Citrus, hoppy"},
        {"name": "Anchor Steam Ale", "abv": 4.9, "origin": "USA", "profile": "Malty, crisp"},
        {"name": "New Belgium Fat Tire", "abv": 5.2, "origin": "USA", "profile": "Toasty, smooth"},
        {"name": "Bellhaven Best", "abv": 4.1, "origin": "Scotland", "profile": "Smooth, balanced"},
        {"name": "Caledonia Best", "abv": 4.5, "origin": "Scotland", "profile": "Malty, smooth"},
        {"name": "Fuller's ESB", "abv": 5.9, "origin": "UK", "profile": "Balanced, malty"},
        {"name": "BrewDog Pale Ale", "abv": 5.4, "origin": "Scotland", "profile": "Hoppy, tropical"},
        {"name": "Marston's Pedigree", "abv": 4.5, "origin": "UK", "profile": "Malty, smooth"},
        {"name": "Timothy Taylor Boltmaker", "abv": 4.8, "origin": "UK", "profile": "Rich, malty"},
        {"name": "Fuller's ESB Gold", "abv": 5.5, "origin": "UK", "profile": "Smooth, balanced"},
        {"name": "Adnams Ghost Ship", "abv": 4.5, "origin": "UK", "profile": "Hoppy, light"},
        {"name": "Goose Island 312", "abv": 5.2, "origin": "USA", "profile": "Wheat-forward, smooth"},
        {"name": "Blue Moon Belgian White", "abv": 5.4, "origin": "USA", "profile": "Citrus, smooth"},
        {"name": "Shock Top Belgian White", "abv": 5.2, "origin": "USA", "profile": "Wheat, citrusy"},
        {"name": "Samuel Smith Nut Brown Ale", "abv": 5.0, "origin": "UK", "profile": "Nutty, smooth"},
        {"name": "Fuller's Honey Dew", "abv": 4.3, "origin": "UK", "profile": "Light, honeyed"},
        {"name": "BrewDog Indie Pale Ale", "abv": 4.2, "origin": "Scotland", "profile": "Crisp, hoppy"},
        {"name": "Adnams Southwold Pale Ale", "abv": 4.3, "origin": "UK", "profile": "Light, smooth"},
        {"name": "Shepherd Neame Spitfire", "abv": 4.5, "origin": "UK", "profile": "Balanced, hoppy"},
        {"name": "Fuller's Organic Honey Dew", "abv": 4.3, "origin": "UK", "profile": "Light, sweet"},
        {"name": "Fuller's Discovery", "abv": 4.5, "origin": "UK", "profile": "Fruity, smooth"}
    ]
    "ipa": [
        {"name": "Sierra Nevada Torpedo Extra IPA", "abv": 7.2, "origin": "USA", "profile": "Hoppy, piney"},
        {"name": "Stone IPA", "abv": 6.9, "origin": "USA", "profile": "Bold, citrusy"},
        {"name": "BrewDog Punk IPA", "abv": 5.6, "origin": "Scotland", "profile": "Tropical, hoppy"},
        {"name": "Lagunitas IPA", "abv": 6.2, "origin": "USA", "profile": "Citrus, hoppy"},
        {"name": "Ballast Point Sculpin IPA", "abv": 7.0, "origin": "USA", "profile": "Tropical, crisp"},
        {"name": "Dogfish Head 60 Minute IPA", "abv": 6.0, "origin": "USA", "profile": "Balanced, hoppy"},
        {"name": "Dogfish Head 90 Minute IPA", "abv": 9.0, "origin": "USA", "profile": "Strong, hoppy"},
        {"name": "Founders All Day IPA", "abv": 4.7, "origin": "USA", "profile": "Light, citrusy"},
        {"name": "Goose Island IPA", "abv": 5.9, "origin": "USA", "profile": "Hoppy, floral"},
        {"name": "Brooklyn East IPA", "abv": 6.9, "origin": "USA", "profile": "Balanced, hoppy"},
        {"name": "Stone Ruination IPA", "abv": 8.2, "origin": "USA", "profile": "Very hoppy, bitter"},
        {"name": "BrewDog Elvis Juice", "abv": 6.5, "origin": "Scotland", "profile": "Grapefruit, hoppy"},
        {"name": "Lagunitas Little Sumpin' Sumpin' Ale", "abv": 7.5, "origin": "USA", "profile": "Smooth, hoppy"},
        {"name": "Bell's Two Hearted Ale", "abv": 7.0, "origin": "USA", "profile": "Hoppy, piney"},
        {"name": "Deschutes Fresh Squeezed IPA", "abv": 6.4, "origin": "USA", "profile": "Citrus, juicy"},
        {"name": "Evil Twin Even More Jesus IPA", "abv": 9.5, "origin": "Denmark/USA", "profile": "Strong, hoppy"},
        {"name": "Ballast Point Grapefruit Sculpin", "abv": 7.0, "origin": "USA", "profile": "Citrus, hoppy"},
        {"name": "Oskar Blues Dale's Pale Ale", "abv": 6.5, "origin": "USA", "profile": "Malty, hoppy"},
        {"name": "Sierra Nevada Hazy Little Thing", "abv": 6.7, "origin": "USA", "profile": "Juicy, hazy"},
        {"name": "Founders Centennial IPA", "abv": 7.2, "origin": "USA", "profile": "Citrus, bitter"},
        {"name": "Lagunitas Hop Stoopid", "abv": 8.0, "origin": "USA", "profile": "Strong, hoppy"},
        {"name": "Stone Go To IPA", "abv": 4.8, "origin": "USA", "profile": "Light, citrusy"},
        {"name": "Green Flash West Coast IPA", "abv": 7.0, "origin": "USA", "profile": "Hoppy, piney"},
        {"name": "Dogfish Head Flesh & Blood IPA", "abv": 6.2, "origin": "USA", "profile": "Citrus, juicy"},
        {"name": "Firestone Walker Union Jack IPA", "abv": 7.0, "origin": "USA", "profile": "Bitter, hoppy"},
        {"name": "Lagunitas Maximus", "abv": 8.2, "origin": "USA", "profile": "Strong, malty"},
        {"name": "Ballast Point Dorado IPA", "abv": 7.0, "origin": "USA", "profile": "Tropical, hoppy"},
        {"name": "Sierra Nevada Celebration IPA", "abv": 6.8, "origin": "USA", "profile": "Citrus, piney"},
        {"name": "BrewDog Hazy Jane", "abv": 5.0, "origin": "Scotland", "profile": "Juicy, tropical"},
        {"name": "Green Flash Le Freak", "abv": 9.2, "origin": "USA", "profile": "Strong, hoppy"},
        {"name": "Stone Delicious IPA", "abv": 7.7, "origin": "USA", "profile": "Citrus, hoppy"},
        {"name": "Dogfish Head Head Hunter IPA", "abv": 7.0, "origin": "USA", "profile": "Hoppy, bitter"},
        {"name": "Ballast Point IPA", "abv": 7.0, "origin": "USA", "profile": "Citrus, piney"},
        {"name": "Founders Centennial IPA", "abv": 7.2, "origin": "USA", "profile": "Bitter, citrus"},
        {"name": "Lagunitas IPA", "abv": 6.2, "origin": "USA", "profile": "Hoppy, citrus"},
        {"name": "Stone IPA", "abv": 6.9, "origin": "USA", "profile": "Bold, bitter"},
        {"name": "Sierra Nevada Pale Ale", "abv": 5.6, "origin": "USA", "profile": "Balanced, citrusy"},
        {"name": "BrewDog Punk IPA", "abv": 5.6, "origin": "Scotland", "profile": "Tropical, hoppy"},
        {"name": "Dogfish Head 60 Minute IPA", "abv": 6.0, "origin": "USA", "profile": "Hoppy, balanced"},
        {"name": "Dogfish Head 90 Minute IPA", "abv": 9.0, "origin": "USA", "profile": "Strong, hoppy"},
        {"name": "Founders All Day IPA", "abv": 4.7, "origin": "USA", "profile": "Light, citrusy"},
        {"name": "Goose Island IPA", "abv": 5.9, "origin": "USA", "profile": "Hoppy, floral"},
        {"name": "Brooklyn East IPA", "abv": 6.9, "origin": "USA", "profile": "Balanced, hoppy"},
        {"name": "Stone Ruination IPA", "abv": 8.2, "origin": "USA", "profile": "Very hoppy, bitter"},
        {"name": "BrewDog Elvis Juice", "abv": 6.5, "origin": "Scotland", "profile": "Grapefruit, hoppy"},
        {"name": "Lagunitas Little Sumpin' Sumpin' Ale", "abv": 7.5, "origin": "USA", "profile": "Smooth, hoppy"},
        {"name": "Bell's Two Hearted Ale", "abv": 7.0, "origin": "USA", "profile": "Hoppy, piney"},
        {"name": "Deschutes Fresh Squeezed IPA", "abv": 6.4, "origin": "USA", "profile": "Citrus, juicy"},
        {"name": "Evil Twin Even More Jesus IPA", "abv": 9.5, "origin": "Denmark/USA", "profile": "Strong, hoppy"},
        {"name": "Ballast Point Grapefruit Sculpin", "abv": 7.0, "origin": "USA", "profile": "Citrus, hoppy"},
        {"name": "Oskar Blues Dale's Pale Ale", "abv": 6.5, "origin": "USA", "profile": "Malty, hoppy"},
        {"name": "Sierra Nevada Hazy Little Thing", "abv": 6.7, "origin": "USA", "profile": "Juicy, hazy"},
        {"name": "Founders Centennial IPA", "abv": 7.2, "origin": "USA", "profile": "Citrus, bitter"},
        {"name": "Lagunitas Hop Stoopid", "abv": 8.0, "origin": "USA", "profile": "Strong, hoppy"},
        {"name": "Stone Go To IPA", "abv": 4.8, "origin": "USA", "profile": "Light, citrusy"},
        {"name": "Green Flash West Coast IPA", "abv": 7.0, "origin": "USA", "profile": "Hoppy, piney"},
        {"name": "Dogfish Head Flesh & Blood IPA", "abv": 6.2, "origin": "USA", "profile": "Citrus, juicy"},
        {"name": "Firestone Walker Union Jack IPA", "abv": 7.0, "origin": "USA", "profile": "Bitter, hoppy"}
    ]
    "stout": [
    {"name": "Guinness Draught", "abv": 4.2, "origin": "Ireland", "profile": "Roasted, creamy, smooth"},
    {"name": "Murphy's Irish Stout", "abv": 4.0, "origin": "Ireland", "profile": "Smooth, chocolatey"},
    {"name": "Beamish Irish Stout", "abv": 4.3, "origin": "Ireland", "profile": "Roasted, bitter, smooth"},
    {"name": "Samuel Smith's Oatmeal Stout", "abv": 5.0, "origin": "UK", "profile": "Oaty, rich, smooth"},
    {"name": "Young's Double Chocolate Stout", "abv": 5.2, "origin": "UK", "profile": "Chocolate, sweet, smooth"},
    {"name": "Old Speckled Hen Stout", "abv": 5.0, "origin": "UK", "profile": "Malty, roasted, smooth"},
    {"name": "Fuller's Vintage Ale Stout", "abv": 6.0, "origin": "UK", "profile": "Roasted, strong, smooth"},
    {"name": "Left Hand Milk Stout Nitro", "abv": 6.0, "origin": "USA", "profile": "Creamy, sweet, roasted"},
    {"name": "Deschutes Obsidian Stout", "abv": 6.4, "origin": "USA", "profile": "Roasted, coffee, chocolate"},
    {"name": "Founders Breakfast Stout", "abv": 8.3, "origin": "USA", "profile": "Coffee, chocolate, rich"},
    {"name": "Young's Special London Stout", "abv": 5.2, "origin": "UK", "profile": "Roasted, bitter, smooth"},
    {"name": "Sierra Nevada Stout", "abv": 5.5, "origin": "USA", "profile": "Roasted, smooth, malty"},
    {"name": "Guinness Extra Stout", "abv": 5.6, "origin": "Ireland", "profile": "Roasted, bold, dry"},
    {"name": "Samuel Smith's Imperial Stout", "abv": 7.0, "origin": "UK", "profile": "Strong, rich, roasted"},
    {"name": "Bells Kalamazoo Stout", "abv": 6.0, "origin": "USA", "profile": "Roasted, chocolate, malty"},
    {"name": "Brooklyn Black Chocolate Stout", "abv": 10.0, "origin": "USA", "profile": "Rich, chocolate, strong"},
    {"name": "North Coast Old Rasputin", "abv": 9.0, "origin": "USA", "profile": "Imperial, roasted, strong"},
    {"name": "O’Hara’s Irish Stout", "abv": 4.3, "origin": "Ireland", "profile": "Smooth, roasted"},
    {"name": "Porterhouse Oyster Stout", "abv": 5.0, "origin": "Ireland", "profile": "Roasted, malty, unique"},
    {"name": "Anchor Porter", "abv": 5.6, "origin": "USA", "profile": "Roasted, chocolate, smooth"},
    {"name": "Young’s Chocolate Stout", "abv": 5.2, "origin": "UK", "profile": "Chocolate, smooth, malty"},
    {"name": "Fuller’s London Porter", "abv": 5.4, "origin": "UK", "profile": "Roasted, malty, balanced"},
    {"name": "Founders Imperial Stout", "abv": 10.2, "origin": "USA", "profile": "Strong, chocolate, coffee"},
    {"name": "Lagunitas Imperial Stout", "abv": 9.0, "origin": "USA", "profile": "Strong, roasted, bitter"},
    {"name": "Evil Twin Even More Jesus Stout", "abv": 10.5, "origin": "Denmark/USA", "profile": "Strong, rich, chocolate"},
    {"name": "Deschutes The Abyss", "abv": 11.0, "origin": "USA", "profile": "Imperial, chocolate, complex"},
    {"name": "Samuel Smith’s Taddy Porter", "abv": 5.0, "origin": "UK", "profile": "Roasted, smooth, malty"},
    {"name": "BrewDog Cocoa Psycho", "abv": 10.0, "origin": "Scotland", "profile": "Chocolate, strong, hoppy"},
    {"name": "Old Speckled Hen Stout", "abv": 5.0, "origin": "UK", "profile": "Malty, smooth, roasted"},
    {"name": "Guinness Nitro Cold Brew", "abv": 4.2, "origin": "Ireland", "profile": "Smooth, creamy, coffee"},
    {"name": "Young’s Double Chocolate", "abv": 5.2, "origin": "UK", "profile": "Chocolate, sweet, smooth"},
    {"name": "Left Hand Wake Up Dead", "abv": 9.0, "origin": "USA", "profile": "Imperial, coffee, roasted"},
    {"name": "North Coast Scrimshaw Porter", "abv": 4.8, "origin": "USA", "profile": "Light, roasted, smooth"},
    {"name": "Samuel Adams Chocolate Bock", "abv": 5.8, "origin": "USA", "profile": "Chocolate, malty, smooth"},
    {"name": "Young’s Winter Warmer Stout", "abv": 5.5, "origin": "UK", "profile": "Roasted, rich, malty"},
    {"name": "Fuller’s Vintage Stout", "abv": 7.0, "origin": "UK", "profile": "Strong, malty, roasted"},
    {"name": "Guinness Foreign Extra Stout", "abv": 7.5, "origin": "Ireland", "profile": "Strong, roasted, bold"},
    {"name": "Brooklyn Black Ops", "abv": 11.1, "origin": "USA", "profile": "Imperial, rich, chocolate"},
    {"name": "O’Hara’s Leann Folláin", "abv": 5.2, "origin": "Ireland", "profile": "Rich, roasted, smooth"},
    {"name": "Bells Expedition Stout", "abv": 10.0, "origin": "USA", "profile": "Imperial, roasted, strong"},
    {"name": "Deschutes Obsidian Stout", "abv": 6.4, "origin": "USA", "profile": "Roasted, coffee, chocolate"},
    {"name": "Founders Breakfast Stout", "abv": 8.3, "origin": "USA", "profile": "Coffee, chocolate, rich"},
    {"name": "O’Hara’s Celtic Stout", "abv": 4.3, "origin": "Ireland", "profile": "Smooth, roasty, malty"},
    {"name": "Guinness Nitro IPA Stout", "abv": 4.2, "origin": "Ireland", "profile": "Roasted, smooth, hoppy"},
    {"name": "Samuel Smith's Imperial Stout", "abv": 7.0, "origin": "UK", "profile": "Strong, rich, roasted"},
    {"name": "Left Hand Milk Stout Nitro", "abv": 6.0, "origin": "USA", "profile": "Creamy, smooth, chocolate"},
    {"name": "Young’s Special London Stout", "abv": 5.2, "origin": "UK", "profile": "Roasted, malty, smooth"},
    {"name": "Anchor Porter", "abv": 5.6, "origin": "USA", "profile": "Chocolate, roasted, smooth"},
    {"name": "Fuller’s London Porter", "abv": 5.4, "origin": "UK", "profile": "Malty, smooth, roasted"},
    {"name": "BrewDog Cocoa Psycho", "abv": 10.0, "origin": "Scotland", "profile": "Chocolate, strong, hoppy"},
    {"name": "North Coast Old Rasputin", "abv": 9.0, "origin": "USA", "profile": "Imperial, roasted, strong"},
    {"name": "Founders Imperial Stout", "abv": 10.2, "origin": "USA", "profile": "Rich, chocolate, coffee"},
    {"name": "Lagunitas Imperial Stout", "abv": 9.0, "origin": "USA", "profile": "Strong, roasted, bitter"},
    {"name": "Evil Twin Even More Jesus Stout", "abv": 10.5, "origin": "Denmark/USA", "profile": "Rich, chocolate, strong"},
    {"name": "Deschutes The Abyss", "abv": 11.0, "origin": "USA", "profile": "Imperial, chocolate, complex"},
    {"name": "Samuel Smith Nut Brown Ale", "abv": 5.0, "origin": "UK", "profile": "Nutty, smooth, roasted"},
    {"name": "Guinness Special Export", "abv": 8.0, "origin": "Ireland", "profile": "Strong, roasted, bold"},
    {"name": "Young’s Chocolate Stout", "abv": 5.2, "origin": "UK", "profile": "Chocolate, sweet, smooth"},
    {"name": "Left Hand Wake Up Dead", "abv": 9.0, "origin": "USA", "profile": "Imperial, coffee, roasted"}
]

    },

    "wine": {
        "red": [
            {"name": "Penfolds Shiraz", "abv": 14.5, "origin": "Australia", "profile": "Dark berries, pepper"},
            {"name": "Yellow Tail Cabernet Sauvignon", "abv": 13.5, "origin": "Australia", "profile": "Smooth, fruity"},
            {"name": "Jacob's Creek Shiraz", "abv": 13.5, "origin": "Australia", "profile": "Medium-bodied, fruity"},
            {"name": "Hardys VR Shiraz", "abv": 13.0, "origin": "Australia", "profile": "Soft, juicy"}
        ],
        "white": [
            {"name": "Cloudy Bay Sauvignon Blanc", "abv": 13.0, "origin": "New Zealand", "profile": "Crisp, fruity"},
            {"name": "Chardonnay Kendall-Jackson", "abv": 13.5, "origin": "USA", "profile": "Vanilla, buttery"},
            {"name": "Santa Margherita Pinot Grigio", "abv": 12.5, "origin": "Italy", "profile": "Dry, crisp"},
            {"name": "Yellow Tail Chardonnay", "abv": 13.0, "origin": "Australia", "profile": "Soft, tropical fruits"}
        ],
        "sparkling": [
            {"name": "Moët & Chandon", "abv": 12.0, "origin": "France", "profile": "Dry, elegant"},
            {"name": "Veuve Clicquot", "abv": 12.0, "origin": "France", "profile": "Fruity, rich"},
            {"name": "Piper-Heidsieck", "abv": 12.5, "origin": "France", "profile": "Crisp, refreshing"},
            {"name": "Laurent-Perrier Cuvée Rosé", "abv": 12.0, "origin": "France", "profile": "Fruity, delicate"}
        ],
        "rosé": [
            {"name": "Whispering Angel Rosé", "abv": 13.0, "origin": "France", "profile": "Fresh, strawberry"},
            {"name": "Miraval Rosé", "abv": 13.0, "origin": "France", "profile": "Crisp, dry"},
            {"name": "Château d’Esclans Rock Angel", "abv": 13.0, "origin": "France", "profile": "Light, floral"},
            {"name": "Beringer White Zinfandel", "abv": 10.5, "origin": "USA", "profile": "Sweet, fruity"}
        ]
    },

    "spirits": {
        "vodka": [
            {"name": "Grey Goose", "abv": 40.0, "origin": "France", "profile": "Smooth, clean"},
            {"name": "Absolut", "abv": 40.0, "origin": "Sweden", "profile": "Neutral, clean"},
            {"name": "Belvedere", "abv": 40.0, "origin": "Poland", "profile": "Soft, creamy"},
            {"name": "Ketel One", "abv": 40.0, "origin": "Netherlands", "profile": "Smooth, crisp"}
        ],
        "gin": [
            {"name": "Hendrick's", "abv": 41.4, "origin": "Scotland", "profile": "Botanical, cucumber, rose"},
            {"name": "Tanqueray", "abv": 43.1, "origin": "UK", "profile": "Juniper-forward, classic"},
            {"name": "Bombay Sapphire", "abv": 40.0, "origin": "UK", "profile": "Botanical, balanced"},
            {"name": "Beefeater", "abv": 40.0, "origin": "UK", "profile": "Classic, juniper"}
        ],
        "whisky": [
            {"name": "Jack Daniel's", "abv": 40.0, "origin": "USA", "profile": "Smooth, vanilla"},
            {"name": "Jameson", "abv": 40.0, "origin": "Ireland", "profile": "Light, nutty"},
            {"name": "Johnnie Walker Black Label", "abv": 40.0, "origin": "Scotland", "profile": "Smoky, rich"},
            {"name": "Glenfiddich 12 Year", "abv": 40.0, "origin": "Scotland", "profile": "Fruity, smooth"}
        ],
        "rum": [
            {"name": "Bacardi White", "abv": 37.5, "origin": "Puerto Rico", "profile": "Light, smooth"},
            {"name": "Captain Morgan Spiced", "abv": 35.0, "origin": "Caribbean", "profile": "Spicy, sweet"},
            {"name": "Mount Gay Eclipse", "abv": 40.0, "origin": "Barbados", "profile": "Rich, caramel"},
            {"name": "Havana Club 3 Year", "abv": 40.0, "origin": "Cuba", "profile": "Light, tropical"}
        ],
        "tequila": [
            {"name": "Jose Cuervo Especial", "abv": 38.0, "origin": "Mexico", "profile": "Agave, smooth"},
            {"name": "Patrón Silver", "abv": 40.0, "origin": "Mexico", "profile": "Clean, citrusy"},
            {"name": "Don Julio Blanco", "abv": 40.0, "origin": "Mexico", "profile": "Fresh, agave"},
            {"name": "Espolon Reposado", "abv": 40.0, "origin": "Mexico", "profile": "Oak, smooth"}
        ],
        "liqueur": [
            {"name": "Baileys Irish Cream", "abv": 17.0, "origin": "Ireland", "profile": "Creamy, sweet"},
            {"name": "Cointreau", "abv": 40.0, "origin": "France", "profile": "Orange, sweet"},
            {"name": "Kahlua", "abv": 20.0, "origin": "Mexico", "profile": "Coffee, sweet"},
            {"name": "Grand Marnier", "abv": 40.0, "origin": "France", "profile": "Orange, rich"}
        ]
    }
}
